"""initial trading schema

Revision ID: e67ef1a7aa2e
Revises: 
Create Date: 2026-09-03 20:44:58.948214
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e67ef1a7aa2e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity_created', 'audit_log', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('bars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'open_time', name='uq_bar_symbol_interval_open')
    )
    op.create_index(op.f('ix_bars_symbol'), 'bars', ['symbol'], unique=False)
    op.create_index('ix_bars_symbol_interval_close', 'bars', ['symbol', 'interval', 'close_time'], unique=False)
    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=False),
    sa.Column('quote_asset', sa.String(length=20), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('step_size', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('min_notional', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('max_leverage', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('strength', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('bar_close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_strategy'), 'signals', ['strategy'], unique=False)
    op.create_index('ix_signals_strategy_created', 'signals', ['strategy', 'created_at'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('approved_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_decisions_action_created', 'risk_decisions', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_risk_decisions_created_at'), 'risk_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_decisions_signal_id'), 'risk_decisions', ['signal_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('risk_decision_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('time_in_force', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_decision_id'], ['risk_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_order_id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index('ix_orders_symbol_status', 'orders', ['symbol', 'status'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('commission', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('commission_asset', sa.String(length=10), nullable=False),
    sa.Column('exchange_trade_id', sa.String(length=64), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_trade_id', name='uq_fills_exchange_trade_id')
    )
    op.create_index(op.f('ix_fills_executed_at'), 'fills', ['executed_at'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_fills_symbol'), 'fills', ['symbol'], unique=False)
    op.create_index('ix_fills_symbol_executed', 'fills', ['symbol', 'executed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fills_symbol_executed', table_name='fills')
    op.drop_index(op.f('ix_fills_symbol'), table_name='fills')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_executed_at'), table_name='fills')
    op.drop_table('fills')
    op.drop_index('ix_orders_symbol_status', table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_risk_decisions_signal_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_created_at'), table_name='risk_decisions')
    op.drop_index('ix_risk_decisions_action_created', table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index('ix_signals_strategy_created', table_name='signals')
    op.drop_index(op.f('ix_signals_strategy'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('instruments')
    op.drop_index('ix_bars_symbol_interval_close', table_name='bars')
    op.drop_index(op.f('ix_bars_symbol'), table_name='bars')
    op.drop_table('bars')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_entity_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
